version: 2.1
jobs:
  build:
    docker:
      - image: cimg/openjdk:18.0.2

    steps:
      - checkout

      - run:
         name: Installing dependencies and compiling the source code
         command: mvn clean install

      - run:
         name: run maven test cases
         command: mvn test

      - store_artifacts:
         path: /home/circleci/project/target/electronic-voting-0.0.1-SNAPSHOT.jar
         destination: electronic-voting-0.0.1-SNAPSHOT.jar
