version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:19-jdk

    steps:
      - checkout

      - run:
         name: Installing dependencies and compiling the source code
         command: mvn clean install

