version: 2.1
jobs:
  build:
    docker:
      - image: cimg/openjdk:18.0.2

    steps:
      - checkout
      - setup_remote_docker

      - run:
         name: Installing dependencies and compiling the source code
         command: mvn clean install

      - run:
         name: run maven test cases
         command: mvn test

      - run:
         name: Build docker image
         command: docker build -t electronic-voting-api .
